AWSTemplateFormatVersion: 2010-09-09

Description: "prometheus template"

Parameters:
  VPC:
    Description: Choose which VPC
    Type: AWS::EC2::VPC::Id
    Default: "vpc-aaaaa"

  VPCSubnets:
    Description: Choose which subnets for EC2
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-aaaaa,subnet-bbbb

  VPCSubnetsALB:
    Description: Choose which subnets for ALB
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-xxxxxx,subnet-yyyyy

  InstanceType:
    Description: Please enter EC2 instance type.
    Type: String
    Default: t3.medium

  AMIId:
    Type: String
    Default: ami-zzzzz

  EnvironmentName:
    Description: Please enter Environment name.
    Type: String
    Default: prometheus

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the ECS EC2 instances
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-launch-template
      LaunchTemplateData:
        KeyName: !Ref KeyName
        ImageId: !Ref AMIId
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - sg-AAAA
          - sg-BBBB
        IamInstanceProfile: 
          Arn : arn:aws:iam::ZZZZZ:instance-profile/ansible-EC2-Instance-Profile
        CreditSpecification:
          CpuCredits: unlimited
        TagSpecifications:
          - ResourceType: instance
            Tags: 
             - Key: Env
               Value: prd

  EC2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-asg
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - subnet-AAA
        - subnet-BBB
      DesiredCapacity: "1"
      MaxSize: "1"
      MinSize: "1"
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      TerminationPolicies: 
        - NewestInstance
      TargetGroupARNs: 
        - arn:aws:elasticloadbalancing:ap-northeast-1:XXXXX:targetgroup/prometheus-tg/31e2996e6a378674
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-asg
          PropagateAtLaunch: true
